var dir_e9c24eb942027799c49e91ebd3f57df1 =
[
    [ "actions.h", "actions_8h.html", "actions_8h" ],
    [ "fonts.h", "fonts_8h.html", "fonts_8h" ],
    [ "images.c", "images_8c.html", "images_8c" ],
    [ "images.h", "images_8h.html", "images_8h" ],
    [ "screens.c", "screens_8c.html", "screens_8c" ],
    [ "screens.h", "screens_8h.html", "screens_8h" ],
    [ "structs.h", "structs_8h.html", null ],
    [ "styles.c", "styles_8c.html", null ],
    [ "styles.h", "styles_8h.html", null ],
    [ "ui.c", "ui_8c.html", "ui_8c" ],
    [ "ui.h", "ui_8h.html", "ui_8h" ],
    [ "ui_font_damion_22.c", "ui__font__damion__22_8c.html", "ui__font__damion__22_8c" ],
    [ "ui_font_damion_36.c", "ui__font__damion__36_8c.html", "ui__font__damion__36_8c" ],
    [ "ui_font_oswald_22.c", "ui__font__oswald__22_8c.html", "ui__font__oswald__22_8c" ],
    [ "ui_font_oswald_36.c", "ui__font__oswald__36_8c.html", "ui__font__oswald__36_8c" ],
    [ "ui_image_clock.c", "ui__image__clock_8c.html", "ui__image__clock_8c" ],
    [ "ui_image_knob.c", "ui__image__knob_8c.html", "ui__image__knob_8c" ],
    [ "ui_image_oil_can.c", "ui__image__oil__can_8c.html", "ui__image__oil__can_8c" ],
    [ "ui_image_oil_can_temp.c", "ui__image__oil__can__temp_8c.html", "ui__image__oil__can__temp_8c" ],
    [ "ui_image_temperature.c", "ui__image__temperature_8c.html", "ui__image__temperature_8c" ],
    [ "ui_image_volt.c", "ui__image__volt_8c.html", "ui__image__volt_8c" ],
    [ "vars.h", "vars_8h.html", "vars_8h" ]
];